// <auto-generated />
using System;
using CUChatNet.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CUChatNet.Api.Migrations
{
    [DbContext(typeof(CUChatNetDbContext))]
    [Migration("20260405074619_AddEsGrupoToChats")]
    partial class AddEsGrupoToChats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CUChatNet.Api.Models.BitacoraEvento", b =>
                {
                    b.Property<long>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("EventoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventoId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DispositivoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("EventoId");

                    b.ToTable("BitacoraEventos", (string)null);
                });

            modelBuilder.Entity("CUChatNet.Api.Models.Chat", b =>
                {
                    b.Property<long>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ChatID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChatId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoConversacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreadoPorUsuarioId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsGrupo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoChat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChatId");

                    b.ToTable("Chats", (string)null);
                });

            modelBuilder.Entity("CUChatNet.Api.Models.ChatParticipante", b =>
                {
                    b.Property<long>("ChatParticipanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChatParticipanteId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Archivado")
                        .HasColumnType("bit");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaLectura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaLimpieza")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUnion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Fijado")
                        .HasColumnType("bit");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silenciado")
                        .HasColumnType("bit");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("ChatParticipanteId");

                    b.HasIndex("ChatId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ChatParticipantes", (string)null);
                });

            modelBuilder.Entity("CUChatNet.Api.Models.ChatUsuario", b =>
                {
                    b.Property<long>("ChatUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChatUsuarioId"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("ChatUsuarioId");

                    b.HasIndex("ChatId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ChatUsuarios", (string)null);
                });

            modelBuilder.Entity("CUChatNet.Api.Models.ClaveDispositivo", b =>
                {
                    b.Property<long>("ClaveDispositivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClaveDispositivoId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("ClavePublica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DispositivoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaRotacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionClave")
                        .HasColumnType("int");

                    b.HasKey("ClaveDispositivoId");

                    b.ToTable("ClavesDispositivo");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.ConfiguracionSistema", b =>
                {
                    b.Property<int>("ConfiguracionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfiguracionId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ApiEndpoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ApiKeySmsEncriptada")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ApiTokenEncriptado")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("AutoArchivarInactividadDias")
                        .HasColumnType("int");

                    b.Property<byte[]>("ClaveSmtpEncriptada")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("E2ERequerido")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxArchivoMB")
                        .HasColumnType("int");

                    b.Property<int>("MaxGrupo")
                        .HasColumnType("int");

                    b.Property<bool>("ModoMantenimiento")
                        .HasColumnType("bit");

                    b.Property<string>("NombreAplicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProveedorSms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PuertoSmtp")
                        .HasColumnType("int");

                    b.Property<string>("ServidorSmtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeoutMensajesMinutos")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioSmtp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConfiguracionId");

                    b.ToTable("ConfiguracionSistema");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.ContactoSilenciadoEstado", b =>
                {
                    b.Property<long>("ContactoSilenciadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ContactoSilenciadoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<long>("ContactoUsuarioId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaSilenciado")
                        .HasColumnType("datetime2");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("ContactoSilenciadoId");

                    b.ToTable("ContactosSilenciadosEstado");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.ContactoUsuario", b =>
                {
                    b.Property<long>("ContactoRelacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ContactoRelacionId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ContactoUsuarioId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaAgregado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SincronizadoAgenda")
                        .HasColumnType("bit");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("ContactoRelacionId");

                    b.HasIndex("ContactoUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ContactosUsuario", (string)null);
                });

            modelBuilder.Entity("CUChatNet.Api.Models.CuentaAcceso", b =>
                {
                    b.Property<long>("CuentaAccesoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CuentaAccesoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CuentaAccesoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DebeCambiarContrasena")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoCuenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashContrasena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UsaOtp")
                        .HasColumnType("bit");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("CuentaAccesoId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("CuentasAcceso", (string)null);
                });

            modelBuilder.Entity("CUChatNet.Api.Models.DispositivoUsuario", b =>
                {
                    b.Property<long>("DispositivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DispositivoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoSeguridad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Confiable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimoUso")
                        .HasColumnType("datetime2");

                    b.Property<string>("HuellaDispositivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navegador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreDispositivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plataforma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SistemaOperativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UltimaIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Verificado")
                        .HasColumnType("bit");

                    b.HasKey("DispositivoId");

                    b.ToTable("DispositivosUsuario");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.EstadoUsuario", b =>
                {
                    b.Property<long>("EstadoUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EstadoUsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EliminadoManual")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("EstadoUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EstadosUsuario");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.EstadoVisualizacion", b =>
                {
                    b.Property<long>("EstadoVisualizacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EstadoVisualizacionId"));

                    b.Property<long>("EstadoUsuarioId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaVisualizacion")
                        .HasColumnType("datetime2");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("EstadoVisualizacionId");

                    b.HasIndex("EstadoUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EstadoVisualizaciones");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.Mensaje", b =>
                {
                    b.Property<long>("MensajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MensajeId"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("Contenido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DispositivoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Editado")
                        .HasColumnType("bit");

                    b.Property<bool>("EliminadoParaTodos")
                        .HasColumnType("bit");

                    b.Property<bool>("Encriptado")
                        .HasColumnType("bit");

                    b.Property<long?>("EsRespuestaA")
                        .HasColumnType("bigint");

                    b.Property<string>("EstadoServidor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaEdicion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RemitenteUsuarioId")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoMensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MensajeId");

                    b.HasIndex("ChatId");

                    b.HasIndex("RemitenteUsuarioId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.MensajeAdjunto", b =>
                {
                    b.Property<long>("AdjuntoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdjuntoId"));

                    b.Property<int?>("Alto")
                        .HasColumnType("int");

                    b.Property<int?>("Ancho")
                        .HasColumnType("int");

                    b.Property<int?>("DuracionSegundos")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<long>("MensajeId")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoAdjunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdjuntoId");

                    b.HasIndex("MensajeId");

                    b.ToTable("MensajeAdjuntos");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.MensajeEstado", b =>
                {
                    b.Property<long>("MensajeEstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MensajeEstadoId"));

                    b.Property<bool>("EliminadoParaMi")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaEliminadoParaMi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVista")
                        .HasColumnType("datetime2");

                    b.Property<long>("MensajeId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("MensajeEstadoId");

                    b.HasIndex("MensajeId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MensajeEstados");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.PoliticaSeguridad", b =>
                {
                    b.Property<int>("PoliticaSeguridadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoliticaSeguridadId"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int>("BloquearTrasIntentosFallidos")
                        .HasColumnType("int");

                    b.Property<bool>("DeteccionCambioDispositivo")
                        .HasColumnType("bit");

                    b.Property<int>("DuracionBloqueoMinutos")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxDispositivosPorUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("RequiereE2E")
                        .HasColumnType("bit");

                    b.Property<int>("RotacionClavesDias")
                        .HasColumnType("int");

                    b.Property<int>("TimeoutLoginSospechosoMin")
                        .HasColumnType("int");

                    b.Property<bool>("VerificacionIdentidad")
                        .HasColumnType("bit");

                    b.HasKey("PoliticaSeguridadId");

                    b.ToTable("PoliticasSeguridad");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolId");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("CUChatNet.Api.Models.Usuario", b =>
                {
                    b.Property<long>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("UsuarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoPerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtensionPais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoCompleto")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Verificado")
                        .HasColumnType("bit");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("CUChatNet.Api.Models.UsuarioRol", b =>
                {
                    b.Property<long>("UsuarioRolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UsuarioRolId"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("UsuarioRolId");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.VerificacionSms", b =>
                {
                    b.Property<long>("VerificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VerificacionId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DispositivoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtensionPais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVerificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Intentos")
                        .HasColumnType("int");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProveedorSms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("VerificacionId");

                    b.ToTable("VerificacionesSms");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.ChatParticipante", b =>
                {
                    b.HasOne("CUChatNet.Api.Models.Chat", "Chat")
                        .WithMany("Participantes")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUChatNet.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.ChatUsuario", b =>
                {
                    b.HasOne("CUChatNet.Api.Models.Chat", "Chat")
                        .WithMany("ChatUsuarios")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUChatNet.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.ContactoUsuario", b =>
                {
                    b.HasOne("CUChatNet.Api.Models.Usuario", "Contacto")
                        .WithMany()
                        .HasForeignKey("ContactoUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CUChatNet.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contacto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.CuentaAcceso", b =>
                {
                    b.HasOne("CUChatNet.Api.Models.Usuario", "Usuario")
                        .WithOne("CuentaAcceso")
                        .HasForeignKey("CUChatNet.Api.Models.CuentaAcceso", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.EstadoUsuario", b =>
                {
                    b.HasOne("CUChatNet.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.EstadoVisualizacion", b =>
                {
                    b.HasOne("CUChatNet.Api.Models.EstadoUsuario", "EstadoUsuario")
                        .WithMany("Visualizaciones")
                        .HasForeignKey("EstadoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUChatNet.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.Mensaje", b =>
                {
                    b.HasOne("CUChatNet.Api.Models.Chat", "Chat")
                        .WithMany("Mensajes")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUChatNet.Api.Models.Usuario", "RemitenteUsuario")
                        .WithMany()
                        .HasForeignKey("RemitenteUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("RemitenteUsuario");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.MensajeAdjunto", b =>
                {
                    b.HasOne("CUChatNet.Api.Models.Mensaje", "Mensaje")
                        .WithMany("Adjuntos")
                        .HasForeignKey("MensajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mensaje");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.MensajeEstado", b =>
                {
                    b.HasOne("CUChatNet.Api.Models.Mensaje", "Mensaje")
                        .WithMany("Estados")
                        .HasForeignKey("MensajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUChatNet.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mensaje");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.UsuarioRol", b =>
                {
                    b.HasOne("CUChatNet.Api.Models.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CUChatNet.Api.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.Chat", b =>
                {
                    b.Navigation("ChatUsuarios");

                    b.Navigation("Mensajes");

                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.EstadoUsuario", b =>
                {
                    b.Navigation("Visualizaciones");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.Mensaje", b =>
                {
                    b.Navigation("Adjuntos");

                    b.Navigation("Estados");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("CUChatNet.Api.Models.Usuario", b =>
                {
                    b.Navigation("CuentaAcceso");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
